name: Get Latest FFDec Release

on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  download-ffdec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest FFDec release
        id: ffdec_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: jindrapetrik/jpexs-decompiler
          token: ${{ github.token }}

      - name: Check current version
        id: check_version
        run: |
            mkdir -p src-tauri/lib
            if [ -f src-tauri/lib/ffdec.jar ]; then
                CURRENT_VERSION=$(unzip -p src-tauri/lib/ffdec.jar project.properties | grep "^version=" | cut -d'=' -f2 | tr -d '[:space:]')
                echo "current_version=version${CURRENT_VERSION}" >> $GITHUB_OUTPUT
            else
                echo "current_version=none" >> $GITHUB_OUTPUT
            fi

      - name: Download and Extract FFDec
        if: steps.check_version.outputs.current_version != steps.ffdec_release.outputs.release
        run: |
          mkdir -p temp
          VERSION_NUM="${{ steps.ffdec_release.outputs.release }}"
          VERSION_NUM="${VERSION_NUM#version}"
          wget -O temp/ffdec.zip https://github.com/jindrapetrik/jpexs-decompiler/releases/download/${{ steps.ffdec_release.outputs.release }}/ffdec_${VERSION_NUM}.zip
          unzip temp/ffdec.zip -d temp/
          mv temp/ffdec.jar src-tauri/lib/
          rm -rf temp

      - name: Commit changes
        if: steps.check_version.outputs.current_version != steps.ffdec_release.outputs.release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update FFDec to ${{ steps.ffdec_release.outputs.release }}"
          file_pattern: 'src-tauri/lib/ffdec.jar'
